"""Multi-level configuration loading (.release.conf format).

Reads configuration from multiple sources and merges them in a fixed
priority order (highest wins):

  1. CLI flags          — ``--deploy-path``, ``--mf-path``, ``--manifest``
  2. Environment vars   — snapshotted once at import time so that a config
                          file loaded later cannot silently shadow them
  3. ``--config FILE``  — an explicit config file passed on the command line
  4. ``<repo>/.release.conf`` — repo-level config (auto-detected)
  5. Built-in defaults  — hard-coded in the ``Config`` dataclass

Config files use a simple ``KEY=VALUE`` format (see ``_parse_conf_file``).
"""

import os
import stat
from dataclasses import dataclass

from .log import log_info, log_warn, log_error

# ---------------------------------------------------------------------------
# Environment variable snapshot
# ---------------------------------------------------------------------------
# Captured once at import time.  This prevents a later-loaded config file
# from overriding a value the operator explicitly set in the environment.
_ENV_SNAPSHOT = {
    "RELEASE_DEFAULT_BRANCH": os.environ.get("RELEASE_DEFAULT_BRANCH", ""),
    "RELEASE_TAG_PREFIX": os.environ.get("RELEASE_TAG_PREFIX", ""),
    "RELEASE_REMOTE": os.environ.get("RELEASE_REMOTE", ""),
    "MODULEFILE_TEMPLATE": os.environ.get("MODULEFILE_TEMPLATE", ""),
    "TOOLSET_MODULEFILE_TEMPLATE": os.environ.get("TOOLSET_MODULEFILE_TEMPLATE", ""),
    "MF_BASE_PATH": os.environ.get("MF_BASE_PATH", ""),
    "TOOLS_MANIFEST": os.environ.get("TOOLS_MANIFEST", ""),
}

# ---------------------------------------------------------------------------
# Config-file key names mapped to their environment variable equivalents.
# Only keys listed here are accepted in .release.conf files; anything else
# triggers a warning so typos don't go unnoticed.
# ---------------------------------------------------------------------------
_CONFIG_KEY_TO_ENV = {
    "DEFAULT_BRANCH": "RELEASE_DEFAULT_BRANCH",
    "TAG_PREFIX": "RELEASE_TAG_PREFIX",
    "REMOTE": "RELEASE_REMOTE",
    "MODULEFILE_TEMPLATE": "MODULEFILE_TEMPLATE",
    "TOOLSET_MODULEFILE_TEMPLATE": "TOOLSET_MODULEFILE_TEMPLATE",
    "MF_BASE_PATH": "MF_BASE_PATH",
    "TOOLS_MANIFEST": "TOOLS_MANIFEST",
}

_KNOWN_KEYS = set(_CONFIG_KEY_TO_ENV.keys())


# ---------------------------------------------------------------------------
# Config dataclass — holds the final merged configuration
# ---------------------------------------------------------------------------
@dataclass
class Config:
    """Resolved configuration values used by both release.py and deploy.py.

    Each field corresponds to a setting that can be specified via defaults,
    config files, environment variables, or CLI flags.
    """

    # Git branch that releases are tagged from (e.g. "main", "master").
    # Config key: DEFAULT_BRANCH | Env: RELEASE_DEFAULT_BRANCH
    default_branch: str = "main"

    # Prefix prepended to version numbers when creating git tags.
    # For example, prefix "v" turns version "1.2.3" into tag "v1.2.3".
    # Config key: TAG_PREFIX | Env: RELEASE_TAG_PREFIX
    tag_prefix: str = "v"

    # Name of the git remote to fetch from and push tags to.
    # Config key: REMOTE | Env: RELEASE_REMOTE
    remote: str = "origin"

    # Absolute path to the root directory where tools are deployed.
    # Each tool gets a subdirectory: <deploy_base_path>/<tool>/<version>/
    # Set via CLI --deploy-path or tools.json "deploy_base_path" field.
    deploy_base_path: str = ""

    # Path to a Tcl modulefile template file.  When set, new modulefiles
    # are generated by substituting placeholders in this template instead
    # of using the built-in default template.
    # Config key: MODULEFILE_TEMPLATE | Env: MODULEFILE_TEMPLATE
    modulefile_template: str = ""

    # Path to a Tcl template used for *toolset* modulefiles.  If unset,
    # toolsets fall back to ``modulefile_template`` and then to the built-in
    # toolset default.  Toolset templates can use ``%TOOL_LOADS%`` and
    # per-tool ``%<tool-name>%`` placeholders.
    # Config key: TOOLSET_MODULEFILE_TEMPLATE | Env: TOOLSET_MODULEFILE_TEMPLATE
    toolset_modulefile_template: str = ""

    # Absolute path to the base directory for Environment Modules files.
    # Modulefiles are written to <mf_base_path>/<tool>/<version>.
    # Falls back to <deploy_base_path>/mf/ when not set.
    # Config key: MF_BASE_PATH | Env: MF_BASE_PATH | CLI: --mf-path
    mf_base_path: str = ""

    # Path to the tools.json manifest file.
    # When empty, defaults to ./tools.json in the current working directory.
    # Config key: TOOLS_MANIFEST | Env: TOOLS_MANIFEST | CLI: --manifest
    tools_manifest: str = ""


def _warn_file_permissions(filepath: str) -> None:
    """Check Unix file permissions and warn if the file is world- or group-readable.

    Config files may contain paths or other sensitive deployment details.
    This nudges the operator toward ``chmod 600`` without blocking execution.
    """
    try:
        st = os.stat(filepath)
        mode = stat.S_IMODE(st.st_mode)
        if mode & (stat.S_IRWXG | stat.S_IRWXO):
            octal = f"{mode:o}"
            log_warn(f"'{filepath}' is accessible by others (mode {octal}). "
                     f"Consider: chmod 600 '{filepath}'")
    except OSError:
        pass


def _parse_conf_file(filepath: str) -> dict:
    """Parse a ``.release.conf`` file and return its key/value pairs.

    File format (one setting per line)::

        # Comments start with '#'
        DEFAULT_BRANCH=main
        TAG_PREFIX="v"          # single or double quotes are stripped
        REMOTE = origin         # whitespace around '=' is ignored

    Only keys listed in ``_KNOWN_KEYS`` are accepted.  Unknown keys emit a
    warning so that typos are caught early rather than silently ignored.

    Returns:
        Dict mapping config key names to their string values.
        Empty dict if the file does not exist or cannot be read.
    """
    result = {}
    try:
        with open(filepath, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                if "=" not in line:
                    continue
                key, _, value = line.partition("=")
                key = key.strip()
                if not key or key.startswith("#"):
                    continue
                # Strip surrounding quotes (single or double)
                value = value.strip()
                if len(value) >= 2:
                    if (value[0] == '"' and value[-1] == '"') or \
                       (value[0] == "'" and value[-1] == "'"):
                        value = value[1:-1]
                value = value.strip()
                if key in _KNOWN_KEYS:
                    result[key] = value
                else:
                    log_warn(f"Unknown config key: {key}")
    except FileNotFoundError:
        pass
    except OSError as e:
        log_warn(f"Cannot read config file '{filepath}': {e}")
    return result


def _apply_conf(config: Config, conf: dict, source_label: str = "config file") -> None:
    """Merge parsed config-file values into an existing ``Config`` object.

    Only keys present in *conf* are written; missing keys leave the
    existing value in *config* untouched.  This allows layered loading
    where each source only overrides what it explicitly sets.
    """
    if "DEFAULT_BRANCH" in conf:
        config.default_branch = conf["DEFAULT_BRANCH"]
    if "TAG_PREFIX" in conf:
        config.tag_prefix = conf["TAG_PREFIX"]
    if "REMOTE" in conf:
        config.remote = conf["REMOTE"]
    if "MODULEFILE_TEMPLATE" in conf:
        config.modulefile_template = conf["MODULEFILE_TEMPLATE"]
    if "TOOLSET_MODULEFILE_TEMPLATE" in conf:
        config.toolset_modulefile_template = conf["TOOLSET_MODULEFILE_TEMPLATE"]
    if "MF_BASE_PATH" in conf:
        config.mf_base_path = conf["MF_BASE_PATH"]
    if "TOOLS_MANIFEST" in conf:
        config.tools_manifest = conf["TOOLS_MANIFEST"]


def load_config(
    config_file: str = "",
    repo_root: str = "",
    cli_deploy_path: str = "",
    cli_mf_path: str = "",
    cli_manifest: str = "",
) -> Config:
    """Build a fully resolved ``Config`` by layering every source.

    Sources are applied in increasing priority so that later layers
    override earlier ones:

      1. **Built-in defaults** — hard-coded in ``Config()``.
      2. **Repo-level config** — ``<repo_root>/.release.conf`` if it exists.
      3. **Explicit config file** — ``--config FILE`` (errors if missing).
      4. **Environment variables** — from the snapshot taken at import time.
      5. **CLI flags** — ``--deploy-path``, ``--mf-path``, ``--manifest``.

    Args:
        config_file:    Path passed via ``--config``.  Must exist if non-empty.
        repo_root:      Git repository root, used to locate the repo-level
                        ``.release.conf``.  Empty string skips this layer.
        cli_deploy_path: Value of ``--deploy-path`` (sets ``deploy_base_path``).
        cli_mf_path:    Value of ``--mf-path`` (sets ``mf_base_path``).
        cli_manifest:   Value of ``--manifest`` (sets ``tools_manifest``).

    Returns:
        A ``Config`` instance with all layers merged.

    Raises:
        SystemExit: If an explicit ``--config`` file does not exist.
    """
    config = Config()

    # Layer 1 — repo-level config (lowest file-based priority)
    if repo_root:
        repo_conf = os.path.join(repo_root, ".release.conf")
        if os.path.isfile(repo_conf):
            _warn_file_permissions(repo_conf)
            log_info(f"Loading config: {repo_conf}")
            _apply_conf(config, _parse_conf_file(repo_conf))

    # Layer 2 — explicit --config file
    if config_file:
        if not os.path.isfile(config_file):
            log_error(f"Config file not found: {config_file}")
            raise SystemExit(1)
        _warn_file_permissions(config_file)
        log_info(f"Loading config: {config_file}")
        _apply_conf(config, _parse_conf_file(config_file))

    # Layer 3 — environment variables (from import-time snapshot)
    if _ENV_SNAPSHOT["RELEASE_DEFAULT_BRANCH"]:
        config.default_branch = _ENV_SNAPSHOT["RELEASE_DEFAULT_BRANCH"]
    if _ENV_SNAPSHOT["RELEASE_TAG_PREFIX"]:
        config.tag_prefix = _ENV_SNAPSHOT["RELEASE_TAG_PREFIX"]
    if _ENV_SNAPSHOT["RELEASE_REMOTE"]:
        config.remote = _ENV_SNAPSHOT["RELEASE_REMOTE"]
    if _ENV_SNAPSHOT["MODULEFILE_TEMPLATE"]:
        config.modulefile_template = _ENV_SNAPSHOT["MODULEFILE_TEMPLATE"]
    if _ENV_SNAPSHOT["TOOLSET_MODULEFILE_TEMPLATE"]:
        config.toolset_modulefile_template = _ENV_SNAPSHOT["TOOLSET_MODULEFILE_TEMPLATE"]
    if _ENV_SNAPSHOT["MF_BASE_PATH"]:
        config.mf_base_path = _ENV_SNAPSHOT["MF_BASE_PATH"]
    if _ENV_SNAPSHOT["TOOLS_MANIFEST"]:
        config.tools_manifest = _ENV_SNAPSHOT["TOOLS_MANIFEST"]

    # Layer 4 — CLI flags (highest priority)
    if cli_deploy_path:
        config.deploy_base_path = cli_deploy_path
    if cli_mf_path:
        config.mf_base_path = cli_mf_path
    if cli_manifest:
        config.tools_manifest = cli_manifest

    return config
